[package]
name = "mini-lsm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.87"
bytes = "1.7.1"
crossbeam-skiplist = "0.1.3"
